model_config: !!python/object:bci_aic3.config.ModelConfig
  name: EEGNet
  num_channels: 8
  num_classes: 2
  sequence_length: 2250
  task_type: MI
training_config: !!python/object:bci_aic3.config.TrainingConfig
  batch_size: 128
  epochs: 100
  learning_rate: 0.001
