# model config
model: # Common parameters
  name: "EEGNet" # {EEGNet | ATCNet}
  task_type: "MI"
  num_classes: 2
  num_channels: 8
  sequence_length: 2250

  # Model-specific parameters
  eegnet:
    F1: 16
    D: 2
    F2: 32
    kernel_1: 85
    kernel_2: 32
    dropout: 0.35

  atcnet:
    num_windows: 7
    tcn_kernel_size: 5
    F1: 4
    D: 2
    conv_pool_size: 7
    tcn_depth: 3


# training config
training:
  epochs: 150
  batch_size: 64
  learning_rate: 0.001
  patience: 40

  # scheduler params
  scheduler_patience: 17
  factor: 0.5

# preprocessing settings
preprocessing:
  notch_freq: 50.0
  bandpass_low: 6.0           # focus on mu rhythm (8-12Hz)
  bandpass_high: 32.0         # include beta rhythm (13-30Hz)
  filter_order: 5             

  tmin: 0.5
  tmax: 7
  sfreq: 250.0

  ica_components: 7
  ica_exclude: [0,1,2,4,5]
