# model config
model:
  name: "ATCNet"      # {ATCNet | EEGNet}
  task_type: "MI"
  num_classes: 2
  num_channels: 8
  sequence_length: 2250


# training config
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  patience: 40

  # scheduler params
  scheduler_patience: 10
  factor: 0.5


# preprocessing settings
preprocessing:

  notch_freq: 50.0
  bandpass_low: 4.0
  bandpass_high: 35.0
  filter_order: 5

  tmin: 0
  tmax: 9
  sfreq: 250.0

  z_threshold: 3
