# model config
model:                # Common parameters
  name: "ATCNet"      # {ATCNet | EEGNet}
  task_type: "MI"
  num_classes: 2
  num_channels: 8
  sequence_length: 2250

  # Model-specific parameters
  eegnet:
    F1: 8
    D: 1
    F2: 8
    kernel_1: 187
    kernel_2: 16
    dropout: 0.3
    
  atcnet:
    num_windows: 6
    tcn_kernel_size: 4
    F1: 4
    D: 2
    conv_pool_size: 7
    tcn_depth: 2

# training config
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  patience: 40

  # scheduler params
  scheduler_patience: 10
  factor: 0.5


# preprocessing settings
preprocessing:

  notch_freq: 50.0
  bandpass_low: 4.0
  bandpass_high: 35.0
  filter_order: 5

  tmin: 0
  tmax: 9
  sfreq: 250.0

  z_threshold: 3
