# model config
model:
  name: "SSVEPformer"        # {EEGNet | DeepConvNet | ShallowConvNet | ATCNet | SSVEPformer | MIN2Net}
  task_type: "SSVEP"
  num_classes: 4
  sequence_length: 1750
  num_channels: 8
  n_csp_components: 6  # Number of CSP components to keep (usually 4-8)


# training config
training:
  epochs: 20
  batch_size: 64
  learning_rate: 0.001
  patience: 10        


# preprocessing settings
preprocessing:
  
  notch_freq: 50.0
  bandpass_low: 2.0
  bandpass_high: 30.0
  filter_order: 5

  tmin: 1
  tmax: 6
  sfreq: 250.0

  # ICA parameters
  ica_n_components: 8  # Use all channels for ICA
  ica_random_state: 42

  # CSP parameters
  n_csp_components: 6  # Number of CSP components to keep (usually 4-8)
