# model config
model:
  name: "EEGNet"
  task_type: "SSVEP"
  num_classes: 4
  sequence_length: 1750
  num_channels: 8

# training config
training:
  epochs: 100
  batch_size: 128
  learning_rate: 0.001

# preprocessing settings
preprocessing:
  notch_freq: 50.0
  lfreq: 1
  hfreq: 40
  baseline: [0.0, 1.0]
  tmin: 2.0
  tmax: 6.0
  sfreq: 250.0
  scaling_factor: 1.0e-6
