# model config
model:
  name: "ATCNet"              # {EEGNet | ATCNet}
  task_type: "SSVEP"
  num_classes: 4
  num_channels: 8  
  sequence_length: 1750

  # Model-specific parameters
  eegnet:
    F1: 32                    
    F2: 64                    # F1 * D 
    D: 2                      # depth multiplier for depthwise conv
    kernel_1: 62              
    kernel_2: 8               
    dropout: 0.3              
  
  atcnet:
    num_windows: 5           
    tcn_kernel_size: 4        
    F1: 8                     
    D: 2                      
    conv_pool_size: 5         
    tcn_depth: 2              


# training config
training:
  epochs: 150
  batch_size: 32
  learning_rate: 0.001
  patience: 30

  # scheduler params
  scheduler_patience: 10
  factor: 0.5


# preprocessing settings
preprocessing:
  
  notch_freq: 50.0
  bandpass_low: 6.0
  bandpass_high: 15.0
  filter_order: 4

  tmin: 0.5
  tmax: 7
  sfreq: 250.0

  ica_components: 6
