# model config
model:
  name: "EEGNet"        # {EEGNet | TSCeption}
  task_type: "SSVEP"
  num_classes: 4
  num_channels: 8
  sequence_length: 1750


# training config
training:
  epochs: 200
  batch_size: 32
  learning_rate: 0.0005
  patience: 50     

  # scheduler params
  scheduler_patience: 10
  factor: 0.3


# preprocessing settings
preprocessing:
  
  notch_freq: 50.0
  bandpass_low: 5.0
  bandpass_high: 40.0
  filter_order: 4

  tmin: 0.5
  tmax: 6.5
  sfreq: 250.0

  z_threshold: 3

