# model config
model:
  name: "EEGNet"        # {EEGNet | TSCeption}
  task_type: "SSVEP"
  num_classes: 4
  num_channels: 8
  sequence_length: 1750

  # Model-specific parameters
  eegnet:
    F1: 16                # number of temporal filters
    F2: 32                # number of spatial filters (F1 * D)
    D: 2                  # depth multiplier for depthwise conv
    kernel_1: 125         # ~1 second at 250Hz for temporal conv
    kernel_2: 8           # spatial kernel size (all channels)
    dropout: 0.25
    
  atcnet:
    num_windows: 6
    tcn_kernel_size: 4
    F1: 4
    D: 2
    conv_pool_size: 7
    tcn_depth: 2


# training config
training:
  epochs: 200
  batch_size: 32
  learning_rate: 0.0005
  patience: 50     

  # scheduler params
  scheduler_patience: 10
  factor: 0.3


# preprocessing settings
preprocessing:
  
  notch_freq: 50.0
  bandpass_low: 5.0
  bandpass_high: 40.0
  filter_order: 4

  tmin: 0.5
  tmax: 6.5
  sfreq: 250.0

  z_threshold: 3

